# version: '3.8'

services:
  app1:
    build: .
    image: golang:1.22-alpine
    ports:
      - "5001:5000" # Exposing each app on a unique port
    environment:
      - SECRET_KEY=${SECRET_KEY}
    volumes:
      - app1_data:/app/data
      - app1_cargo:/app/cargo_files

  app2:
    build: .
    image: golang:1.22-alpine
    ports:
      - "5002:5000"
    environment:
      - SECRET_KEY=${SECRET_KEY}
    volumes:
      - app2_data:/app/data
      - app2_cargo:/app/cargo_files

  app3:
    build: .
    image: golang:1.22-alpine
    ports:
      - "5003:5000"
    environment:
      - SECRET_KEY=${SECRET_KEY}
    volumes:
      - app3_data:/app/data
      - app3_cargo:/app/cargo_files

  app4:
    build: .
    image: golang:1.22-alpine
    ports:
      - "5004:5000"
    environment:
      - SECRET_KEY=${SECRET_KEY}
    volumes:
      - app4_data:/app/data
      - app4_cargo:/app/cargo_files

# Defining separate volumes for each app
volumes:
  app1_data:
  app1_cargo:
  app2_data:
  app2_cargo:
  app3_data:
  app3_cargo:
  app4_data:
  app4_cargo:
