# version: '3.8'

services:
  app1:
    build: .
    image: golang:1.22-alpine
    ports:
      - "5001:5000" # Exposing each app on a unique port
    environment:
      - SECRET_KEY=${SECRET_KEY}
    volumes:
      - app1_data:/app/data
      - app1_cargo:/app/cargo_files

# Defining separate volumes for each app
volumes:
  app1_data:
  app1_cargo:
